import { z } from "zod";
import { LocationId, NpcId } from "./ids";
import { Condition } from "./condition";

/** A place the player can be (SCHEMA.md §2). Top-down, vector-described. */
export const Vec2 = z.object({ x: z.number(), y: z.number() });
export type Vec2 = z.infer<typeof Vec2>;

/**
 * VectorShape: hand-authored or layout-helper produced — never free-generated by the
 * content pipeline (SCHEMA.md §2). Prefer rect/circle; use path sparingly.
 */
export const VectorShape = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("rect"),
    at: Vec2,
    w: z.number(),
    h: z.number(),
    fill: z.string(),
    stroke: z.string().optional(),
  }),
  z.object({
    kind: z.literal("circle"),
    at: Vec2,
    r: z.number(),
    fill: z.string(),
    stroke: z.string().optional(),
  }),
  z.object({
    kind: z.literal("path"),
    points: z.array(Vec2).min(2),
    stroke: z.string(),
    fill: z.string().optional(),
  }),
]);
export type VectorShape = z.infer<typeof VectorShape>;

export const Exit = z.object({
  at: Vec2,
  toLocationId: LocationId,
  spawnAt: Vec2,
  label: z.string().max(40),
  requires: z.array(Condition).default([]),
});
export type Exit = z.infer<typeof Exit>;

export const Location = z.object({
  id: LocationId,
  name: z.string().max(60),
  mood: z.string().max(280),
  bounds: z.object({ w: z.number(), h: z.number() }),
  art: z.array(VectorShape).max(120),
  exits: z.array(Exit).default([]),
  npcSpawns: z.array(z.object({ npcId: NpcId, at: Vec2 })).default([]),
  ambientText: z.array(z.string().max(160)).default([]),
});
export type Location = z.infer<typeof Location>;
